[package]
name = "titanium-rune"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "titanium-rune"
test = false
benchmark = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
cc = "1.2.60"
bindgen = "0.72.1"

[dependencies]
acpi = { version = "6.1.1", default-features = false, features = ["alloc", "aml"] }
bitfield = "0.19.4"
crossbeam = { version = "0.8.4", default-features = false, features = ["alloc", "nightly"] }
fixed = "1.31.0"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
limine = "0.6.3"
linked_list_allocator = "0.10.6"
spin = "0.10.0"
uart_16550 = "0.4.0"
volatile = "0.6.1"
x86_64 = { version = "0.15.4", features = ["instructions"] }
uacpi = { path = "uacpi" }
