/* automatically generated by rust-bindgen 0.72.1 */

pub type uacpi_u8 = u8;
pub type uacpi_u16 = u16;
pub type uacpi_u32 = u32;
pub type uacpi_u64 = u64;
pub type uacpi_bool = bool;
pub type uacpi_size = usize;
pub type uacpi_char = ::core::ffi::c_char;
pub const uacpi_status_UACPI_STATUS_OK: uacpi_status = 0;
pub const uacpi_status_UACPI_STATUS_MAPPING_FAILED: uacpi_status = 1;
pub const uacpi_status_UACPI_STATUS_OUT_OF_MEMORY: uacpi_status = 2;
pub const uacpi_status_UACPI_STATUS_BAD_CHECKSUM: uacpi_status = 3;
pub const uacpi_status_UACPI_STATUS_INVALID_SIGNATURE: uacpi_status = 4;
pub const uacpi_status_UACPI_STATUS_INVALID_TABLE_LENGTH: uacpi_status = 5;
pub const uacpi_status_UACPI_STATUS_NOT_FOUND: uacpi_status = 6;
pub const uacpi_status_UACPI_STATUS_INVALID_ARGUMENT: uacpi_status = 7;
pub const uacpi_status_UACPI_STATUS_UNIMPLEMENTED: uacpi_status = 8;
pub const uacpi_status_UACPI_STATUS_ALREADY_EXISTS: uacpi_status = 9;
pub const uacpi_status_UACPI_STATUS_INTERNAL_ERROR: uacpi_status = 10;
pub const uacpi_status_UACPI_STATUS_TYPE_MISMATCH: uacpi_status = 11;
pub const uacpi_status_UACPI_STATUS_INIT_LEVEL_MISMATCH: uacpi_status = 12;
pub const uacpi_status_UACPI_STATUS_NAMESPACE_NODE_DANGLING: uacpi_status = 13;
pub const uacpi_status_UACPI_STATUS_NO_HANDLER: uacpi_status = 14;
pub const uacpi_status_UACPI_STATUS_NO_RESOURCE_END_TAG: uacpi_status = 15;
pub const uacpi_status_UACPI_STATUS_COMPILED_OUT: uacpi_status = 16;
pub const uacpi_status_UACPI_STATUS_HARDWARE_TIMEOUT: uacpi_status = 17;
pub const uacpi_status_UACPI_STATUS_TIMEOUT: uacpi_status = 18;
pub const uacpi_status_UACPI_STATUS_OVERRIDDEN: uacpi_status = 19;
pub const uacpi_status_UACPI_STATUS_DENIED: uacpi_status = 20;
pub const uacpi_status_UACPI_STATUS_AML_UNDEFINED_REFERENCE: uacpi_status =
  251592704;
pub const uacpi_status_UACPI_STATUS_AML_INVALID_NAMESTRING: uacpi_status =
  251592705;
pub const uacpi_status_UACPI_STATUS_AML_OBJECT_ALREADY_EXISTS: uacpi_status =
  251592706;
pub const uacpi_status_UACPI_STATUS_AML_INVALID_OPCODE: uacpi_status =
  251592707;
pub const uacpi_status_UACPI_STATUS_AML_INCOMPATIBLE_OBJECT_TYPE: uacpi_status =
  251592708;
pub const uacpi_status_UACPI_STATUS_AML_BAD_ENCODING: uacpi_status = 251592709;
pub const uacpi_status_UACPI_STATUS_AML_OUT_OF_BOUNDS_INDEX: uacpi_status =
  251592710;
pub const uacpi_status_UACPI_STATUS_AML_SYNC_LEVEL_TOO_HIGH: uacpi_status =
  251592711;
pub const uacpi_status_UACPI_STATUS_AML_INVALID_RESOURCE: uacpi_status =
  251592712;
pub const uacpi_status_UACPI_STATUS_AML_LOOP_TIMEOUT: uacpi_status = 251592713;
pub const uacpi_status_UACPI_STATUS_AML_CALL_STACK_DEPTH_LIMIT: uacpi_status =
  251592714;
pub type uacpi_status = ::core::ffi::c_uint;
pub type uacpi_cpu_flags = ::core::ffi::c_ulong;
pub type uacpi_interrupt_state = ::core::ffi::c_ulong;
pub type uacpi_thread_id = *mut ::core::ffi::c_void;
#[doc = " Super verbose logging, every op & uop being processed is logged.\n Mostly useful for tracking down hangs/lockups."]
pub const uacpi_log_level_UACPI_LOG_DEBUG: uacpi_log_level = 5;
#[doc = " A little verbose, every operation region access is traced with a bit of\n extra information on top."]
pub const uacpi_log_level_UACPI_LOG_TRACE: uacpi_log_level = 4;
#[doc = " Only logs the bare minimum information about state changes and/or\n initialization progress."]
pub const uacpi_log_level_UACPI_LOG_INFO: uacpi_log_level = 3;
#[doc = " Logs recoverable errors and/or non-important aborts."]
pub const uacpi_log_level_UACPI_LOG_WARN: uacpi_log_level = 2;
#[doc = " Logs only critical errors that might affect the ability to initialize or\n prevent stable runtime."]
pub const uacpi_log_level_UACPI_LOG_ERROR: uacpi_log_level = 1;
pub type uacpi_log_level = ::core::ffi::c_uint;
pub type uacpi_phys_addr = uacpi_u64;
pub type uacpi_io_addr = uacpi_u64;
pub type uacpi_handle = *mut ::core::ffi::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uacpi_pci_address {
  pub segment: uacpi_u16,
  pub bus: uacpi_u8,
  pub device: uacpi_u8,
  pub function: uacpi_u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of uacpi_pci_address"]
    [::core::mem::size_of::<uacpi_pci_address>() - 6usize];
  ["Alignment of uacpi_pci_address"]
    [::core::mem::align_of::<uacpi_pci_address>() - 2usize];
  ["Offset of field: uacpi_pci_address::segment"]
    [::core::mem::offset_of!(uacpi_pci_address, segment) - 0usize];
  ["Offset of field: uacpi_pci_address::bus"]
    [::core::mem::offset_of!(uacpi_pci_address, bus) - 2usize];
  ["Offset of field: uacpi_pci_address::device"]
    [::core::mem::offset_of!(uacpi_pci_address, device) - 3usize];
  ["Offset of field: uacpi_pci_address::function"]
    [::core::mem::offset_of!(uacpi_pci_address, function) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct uacpi_firmware_request {
  pub type_: uacpi_u8,
  pub __bindgen_anon_1: uacpi_firmware_request__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union uacpi_firmware_request__bindgen_ty_1 {
  pub breakpoint: uacpi_firmware_request__bindgen_ty_1__bindgen_ty_1,
  pub fatal: uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uacpi_firmware_request__bindgen_ty_1__bindgen_ty_1 {
  pub ctx: uacpi_handle,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of uacpi_firmware_request__bindgen_ty_1__bindgen_ty_1"]
    [::core::mem::size_of::<uacpi_firmware_request__bindgen_ty_1__bindgen_ty_1>(
    ) - 8usize];
  ["Alignment of uacpi_firmware_request__bindgen_ty_1__bindgen_ty_1"]
    [::core::mem::align_of::<uacpi_firmware_request__bindgen_ty_1__bindgen_ty_1>(
    ) - 8usize];
  ["Offset of field: uacpi_firmware_request__bindgen_ty_1__bindgen_ty_1::ctx"]
    [::core::mem::offset_of!(
      uacpi_firmware_request__bindgen_ty_1__bindgen_ty_1,
      ctx
    ) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2 {
  pub type_: uacpi_u8,
  pub code: uacpi_u32,
  pub arg: uacpi_u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2"]
    [::core::mem::size_of::<uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2>(
    ) - 16usize];
  ["Alignment of uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2"]
    [::core::mem::align_of::<uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2>(
    ) - 8usize];
  ["Offset of field: uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2::type_"] [:: core :: mem :: offset_of ! (uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2 , type_) - 0usize] ;
  ["Offset of field: uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2::code"]
    [::core::mem::offset_of!(
      uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2,
      code
    ) - 4usize];
  ["Offset of field: uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2::arg"]
    [::core::mem::offset_of!(
      uacpi_firmware_request__bindgen_ty_1__bindgen_ty_2,
      arg
    ) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of uacpi_firmware_request__bindgen_ty_1"]
    [::core::mem::size_of::<uacpi_firmware_request__bindgen_ty_1>() - 16usize];
  ["Alignment of uacpi_firmware_request__bindgen_ty_1"]
    [::core::mem::align_of::<uacpi_firmware_request__bindgen_ty_1>() - 8usize];
  ["Offset of field: uacpi_firmware_request__bindgen_ty_1::breakpoint"][::core::mem::offset_of!(
    uacpi_firmware_request__bindgen_ty_1,
    breakpoint
  )
    - 0usize];
  ["Offset of field: uacpi_firmware_request__bindgen_ty_1::fatal"][::core::mem::offset_of!(
    uacpi_firmware_request__bindgen_ty_1,
    fatal
  ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of uacpi_firmware_request"]
    [::core::mem::size_of::<uacpi_firmware_request>() - 24usize];
  ["Alignment of uacpi_firmware_request"]
    [::core::mem::align_of::<uacpi_firmware_request>() - 8usize];
  ["Offset of field: uacpi_firmware_request::type_"]
    [::core::mem::offset_of!(uacpi_firmware_request, type_) - 0usize];
};
pub type uacpi_interrupt_ret = uacpi_u32;
pub type uacpi_interrupt_handler = ::core::option::Option<
  unsafe extern "C" fn(arg1: uacpi_handle) -> uacpi_interrupt_ret,
>;
unsafe extern "C" {
  pub fn uacpi_kernel_get_rsdp(
    out_rsdp_address: *mut uacpi_phys_addr,
  ) -> uacpi_status;
}
unsafe extern "C" {
  #[doc = " Map a physical memory range starting at 'addr' with length 'len', and return\n a virtual address that can be used to access it.\n\n NOTE: 'addr' may be misaligned, in this case the host is expected to round it\n       down to the nearest page-aligned boundary and map that, while making\n       sure that at least 'len' bytes are still mapped starting at 'addr'. The\n       return value preserves the misaligned offset.\n\n       Example for uacpi_kernel_map(0x1ABC, 0xF00):\n           1. Round down the 'addr' we got to the nearest page boundary.\n              Considering a PAGE_SIZE of 4096 (or 0x1000), 0x1ABC rounded down\n              is 0x1000, offset within the page is 0x1ABC - 0x1000 => 0xABC\n           2. Requested 'len' is 0xF00 bytes, but we just rounded the address\n              down by 0xABC bytes, so add those on top. 0xF00 + 0xABC => 0x19BC\n           3. Round up the final 'len' to the nearest PAGE_SIZE boundary, in\n              this case 0x19BC is 0x2000 bytes (2 pages if PAGE_SIZE is 4096)\n           4. Call the VMM to map the aligned address 0x1000 (from step 1)\n              with length 0x2000 (from step 3). Let's assume the returned\n              virtual address for the mapping is 0xF000.\n           5. Add the original offset within page 0xABC (from step 1) to the\n              resulting virtual address 0xF000 + 0xABC => 0xFABC. Return it\n              to uACPI."]
  pub fn uacpi_kernel_map(
    addr: uacpi_phys_addr,
    len: uacpi_size,
  ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
  #[doc = " Unmap a virtual memory range at 'addr' with a length of 'len' bytes.\n\n NOTE: 'addr' may be misaligned, see the comment above 'uacpi_kernel_map'.\n       Similar steps to uacpi_kernel_map can be taken to retrieve the\n       virtual address originally returned by the VMM for this mapping\n       as well as its true length."]
  pub fn uacpi_kernel_unmap(addr: *mut ::core::ffi::c_void, len: uacpi_size);
}
unsafe extern "C" {
  pub fn uacpi_kernel_log(arg1: uacpi_log_level, arg2: *const uacpi_char);
}
unsafe extern "C" {
  #[doc = " Open a PCI device at 'address' for reading & writing.\n\n The device at 'address' might not actually exist on the system, in this case\n the api is allowed to return UACPI_STATUS_NOT_FOUND to indicate that, this\n error is handled gracefully by creating a dummy device internally that always\n returns 0xFF on reads and is no-op for writes. This is to support a common\n pattern in AML that probes for 0xFF reads to detect whether a device exists.\n\n The handle returned via 'out_handle' is used to perform IO on the\n configuration space of the device."]
  pub fn uacpi_kernel_pci_device_open(
    address: uacpi_pci_address,
    out_handle: *mut uacpi_handle,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_pci_device_close(arg1: uacpi_handle);
}
unsafe extern "C" {
  #[doc = " Read & write the configuration space of a previously open PCI device."]
  pub fn uacpi_kernel_pci_read8(
    device: uacpi_handle,
    offset: uacpi_size,
    value: *mut uacpi_u8,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_pci_read16(
    device: uacpi_handle,
    offset: uacpi_size,
    value: *mut uacpi_u16,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_pci_read32(
    device: uacpi_handle,
    offset: uacpi_size,
    value: *mut uacpi_u32,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_pci_write8(
    device: uacpi_handle,
    offset: uacpi_size,
    value: uacpi_u8,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_pci_write16(
    device: uacpi_handle,
    offset: uacpi_size,
    value: uacpi_u16,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_pci_write32(
    device: uacpi_handle,
    offset: uacpi_size,
    value: uacpi_u32,
  ) -> uacpi_status;
}
unsafe extern "C" {
  #[doc = " Map a SystemIO address at [base, base + len) and return a kernel-implemented\n handle that can be used for reading and writing the IO range.\n\n NOTE: The x86 architecture uses the in/out family of instructions\n       to access the SystemIO address space."]
  pub fn uacpi_kernel_io_map(
    base: uacpi_io_addr,
    len: uacpi_size,
    out_handle: *mut uacpi_handle,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_io_unmap(handle: uacpi_handle);
}
unsafe extern "C" {
  #[doc = " Read/Write the IO range mapped via uacpi_kernel_io_map\n at a 0-based 'offset' within the range.\n\n NOTE:\n The x86 architecture uses the in/out family of instructions\n to access the SystemIO address space.\n\n You are NOT allowed to break e.g. a 4-byte access into four 1-byte accesses.\n Hardware ALWAYS expects accesses to be of the exact width."]
  pub fn uacpi_kernel_io_read8(
    arg1: uacpi_handle,
    offset: uacpi_size,
    out_value: *mut uacpi_u8,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_io_read16(
    arg1: uacpi_handle,
    offset: uacpi_size,
    out_value: *mut uacpi_u16,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_io_read32(
    arg1: uacpi_handle,
    offset: uacpi_size,
    out_value: *mut uacpi_u32,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_io_write8(
    arg1: uacpi_handle,
    offset: uacpi_size,
    in_value: uacpi_u8,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_io_write16(
    arg1: uacpi_handle,
    offset: uacpi_size,
    in_value: uacpi_u16,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_io_write32(
    arg1: uacpi_handle,
    offset: uacpi_size,
    in_value: uacpi_u32,
  ) -> uacpi_status;
}
unsafe extern "C" {
  #[doc = " Allocate a block of memory of 'size' bytes.\n The contents of the allocated memory are unspecified."]
  pub fn uacpi_kernel_alloc(size: uacpi_size) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
  pub fn uacpi_kernel_free(mem: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
  #[doc = " Returns the number of nanosecond ticks elapsed since boot,\n strictly monotonic."]
  pub fn uacpi_kernel_get_nanoseconds_since_boot() -> uacpi_u64;
}
unsafe extern "C" {
  #[doc = " Spin for N microseconds."]
  pub fn uacpi_kernel_stall(usec: uacpi_u8);
}
unsafe extern "C" {
  #[doc = " Sleep for N milliseconds."]
  pub fn uacpi_kernel_sleep(msec: uacpi_u64);
}
unsafe extern "C" {
  #[doc = " Create/free an opaque non-recursive kernel mutex object."]
  pub fn uacpi_kernel_create_mutex() -> uacpi_handle;
}
unsafe extern "C" {
  pub fn uacpi_kernel_free_mutex(arg1: uacpi_handle);
}
unsafe extern "C" {
  #[doc = " Create/free an opaque kernel (semaphore-like) event object."]
  pub fn uacpi_kernel_create_event() -> uacpi_handle;
}
unsafe extern "C" {
  pub fn uacpi_kernel_free_event(arg1: uacpi_handle);
}
unsafe extern "C" {
  #[doc = " Returns a unique identifier of the currently executing thread.\n\n The returned thread id cannot be UACPI_THREAD_ID_NONE."]
  pub fn uacpi_kernel_get_thread_id() -> uacpi_thread_id;
}
unsafe extern "C" {
  #[doc = " Disable interrupts and return an kernel-defined value representing the\n \"before\" state. This value is used in the subsequent call to restore the\n prior state.\n\n Note that this is talking about ALL interrupts on the current CPU, not just\n those installed by uACPI. This is typically achieved by executing the 'cli'\n instruction on x86, 'msr daifset, #3' on aarch64 etc."]
  pub fn uacpi_kernel_disable_interrupts() -> uacpi_interrupt_state;
}
unsafe extern "C" {
  #[doc = " Restore the state of the interrupt flags to the kernel-defined value provided\n in 'state'."]
  pub fn uacpi_kernel_restore_interrupts(state: uacpi_interrupt_state);
}
unsafe extern "C" {
  #[doc = " Try to acquire the mutex with a millisecond timeout.\n\n The timeout value has the following meanings:\n 0x0000 - Attempt to acquire the mutex once, in a non-blocking manner\n 0x0001...0xFFFE - Attempt to acquire the mutex for at least 'timeout'\n                   milliseconds\n 0xFFFF - Infinite wait, block until the mutex is acquired\n\n The following are possible return values:\n 1. UACPI_STATUS_OK - successful acquire operation\n 2. UACPI_STATUS_TIMEOUT - timeout reached while attempting to acquire (or the\n                           single attempt to acquire was not successful for\n                           calls with timeout=0)\n 3. Any other value - signifies a host internal error and is treated as such"]
  pub fn uacpi_kernel_acquire_mutex(
    arg1: uacpi_handle,
    arg2: uacpi_u16,
  ) -> uacpi_status;
}
unsafe extern "C" {
  pub fn uacpi_kernel_release_mutex(arg1: uacpi_handle);
}
unsafe extern "C" {
  #[doc = " Try to wait for an event (counter > 0) with a millisecond timeout.\n A timeout value of 0xFFFF implies infinite wait.\n\n The internal counter is decremented by 1 if wait was successful.\n\n A successful wait is indicated by returning UACPI_TRUE."]
  pub fn uacpi_kernel_wait_for_event(
    arg1: uacpi_handle,
    arg2: uacpi_u16,
  ) -> uacpi_bool;
}
unsafe extern "C" {
  #[doc = " Signal the event object by incrementing its internal counter by 1.\n\n This function may be used in interrupt contexts."]
  pub fn uacpi_kernel_signal_event(arg1: uacpi_handle);
}
unsafe extern "C" {
  #[doc = " Reset the event counter to 0."]
  pub fn uacpi_kernel_reset_event(arg1: uacpi_handle);
}
unsafe extern "C" {
  #[doc = " Handle a firmware request.\n\n Currently either a Breakpoint or Fatal operators."]
  pub fn uacpi_kernel_handle_firmware_request(
    arg1: *mut uacpi_firmware_request,
  ) -> uacpi_status;
}
unsafe extern "C" {
  #[doc = " Install an interrupt handler at 'irq', 'ctx' is passed to the provided\n handler for every invocation.\n\n 'out_irq_handle' is set to a kernel-implemented value that can be used to\n refer to this handler from other API."]
  pub fn uacpi_kernel_install_interrupt_handler(
    irq: uacpi_u32,
    arg1: uacpi_interrupt_handler,
    ctx: uacpi_handle,
    out_irq_handle: *mut uacpi_handle,
  ) -> uacpi_status;
}
unsafe extern "C" {
  #[doc = " Uninstall an interrupt handler. 'irq_handle' is the value returned via\n 'out_irq_handle' during installation."]
  pub fn uacpi_kernel_uninstall_interrupt_handler(
    arg1: uacpi_interrupt_handler,
    irq_handle: uacpi_handle,
  ) -> uacpi_status;
}
unsafe extern "C" {
  #[doc = " Create/free a kernel spinlock object.\n\n Unlike other types of locks, spinlocks may be used in interrupt contexts."]
  pub fn uacpi_kernel_create_spinlock() -> uacpi_handle;
}
unsafe extern "C" {
  pub fn uacpi_kernel_free_spinlock(arg1: uacpi_handle);
}
unsafe extern "C" {
  #[doc = " Lock/unlock helpers for spinlocks.\n\n These are expected to disable interrupts, returning the previous state of cpu\n flags, that can be used to possibly re-enable interrupts if they were enabled\n before.\n\n Note that lock is infalliable."]
  pub fn uacpi_kernel_lock_spinlock(arg1: uacpi_handle) -> uacpi_cpu_flags;
}
unsafe extern "C" {
  pub fn uacpi_kernel_unlock_spinlock(
    arg1: uacpi_handle,
    arg2: uacpi_cpu_flags,
  );
}
#[doc = " Schedule a GPE handler method for execution.\n This should be scheduled to run on CPU0 to avoid potential SMI-related\n firmware bugs."]
pub const uacpi_work_type_UACPI_WORK_GPE_EXECUTION: uacpi_work_type = 0;
#[doc = " Schedule a Notify(device) firmware request for execution.\n This can run on any CPU."]
pub const uacpi_work_type_UACPI_WORK_NOTIFICATION: uacpi_work_type = 1;
pub type uacpi_work_type = ::core::ffi::c_uint;
pub type uacpi_work_handler =
  ::core::option::Option<unsafe extern "C" fn(arg1: uacpi_handle)>;
unsafe extern "C" {
  #[doc = " Schedules deferred work for execution.\n Might be invoked from an interrupt context."]
  pub fn uacpi_kernel_schedule_work(
    arg1: uacpi_work_type,
    arg2: uacpi_work_handler,
    ctx: uacpi_handle,
  ) -> uacpi_status;
}
unsafe extern "C" {
  #[doc = " Waits for two types of work to finish:\n 1. All in-flight interrupts installed via uacpi_kernel_install_interrupt_handler\n 2. All work scheduled via uacpi_kernel_schedule_work\n\n Note that the waits must be done in this order specifically."]
  pub fn uacpi_kernel_wait_for_work_completion() -> uacpi_status;
}
