[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
codegen-backend = true

[profile.dev]
codegen-backend = "llvm"

[profile.release]
codegen-backend = "llvm"
