/* automatically generated by rust-bindgen 0.72.1 */
#![allow(unsafe_op_in_unsafe_fn)]

use super::*;

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_get_rsdp(
  out_rsdp_address: *mut uacpi_phys_addr,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.get_rsdp)(out_rsdp_address)
}

#[doc = " Map a physical memory range starting at 'addr' with length 'len', and return\n a virtual address that can be used to access it.\n\n NOTE: 'addr' may be misaligned, in this case the host is expected to round it\n       down to the nearest page-aligned boundary and map that, while making\n       sure that at least 'len' bytes are still mapped starting at 'addr'. The\n       return value preserves the misaligned offset.\n\n       Example for uacpi_kernel_map(0x1ABC, 0xF00):\n           1. Round down the 'addr' we got to the nearest page boundary.\n              Considering a PAGE_SIZE of 4096 (or 0x1000), 0x1ABC rounded down\n              is 0x1000, offset within the page is 0x1ABC - 0x1000 => 0xABC\n           2. Requested 'len' is 0xF00 bytes, but we just rounded the address\n              down by 0xABC bytes, so add those on top. 0xF00 + 0xABC => 0x19BC\n           3. Round up the final 'len' to the nearest PAGE_SIZE boundary, in\n              this case 0x19BC is 0x2000 bytes (2 pages if PAGE_SIZE is 4096)\n           4. Call the VMM to map the aligned address 0x1000 (from step 1)\n              with length 0x2000 (from step 3). Let's assume the returned\n              virtual address for the mapping is 0xF000.\n           5. Add the original offset within page 0xABC (from step 1) to the\n              resulting virtual address 0xF000 + 0xABC => 0xFABC. Return it\n              to uACPI."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_map(
  addr: uacpi_phys_addr,
  len: uacpi_size,
) -> *mut ::core::ffi::c_void {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.map)(addr, len)
}

#[doc = " Unmap a virtual memory range at 'addr' with a length of 'len' bytes.\n\n NOTE: 'addr' may be misaligned, see the comment above 'uacpi_kernel_map'.\n       Similar steps to uacpi_kernel_map can be taken to retrieve the\n       virtual address originally returned by the VMM for this mapping\n       as well as its true length."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_unmap(
  addr: *mut ::core::ffi::c_void,
  len: uacpi_size,
) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.unmap)(addr, len)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_log(
  arg1: uacpi_log_level,
  arg2: *const uacpi_char,
) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.log)(arg1, arg2)
}

#[doc = " Open a PCI device at 'address' for reading & writing.\n\n The device at 'address' might not actually exist on the system, in this case\n the api is allowed to return UACPI_STATUS_NOT_FOUND to indicate that, this\n error is handled gracefully by creating a dummy device internally that always\n returns 0xFF on reads and is no-op for writes. This is to support a common\n pattern in AML that probes for 0xFF reads to detect whether a device exists.\n\n The handle returned via 'out_handle' is used to perform IO on the\n configuration space of the device."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_pci_device_open(
  address: uacpi_pci_address,
  out_handle: *mut uacpi_handle,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.pci_device_open)(address, out_handle)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_pci_device_close(arg1: uacpi_handle) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.pci_device_close)(arg1)
}

#[doc = " Read & write the configuration space of a previously open PCI device."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_pci_read8(
  device: uacpi_handle,
  offset: uacpi_size,
  value: *mut uacpi_u8,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.pci_read8)(device, offset, value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_pci_read16(
  device: uacpi_handle,
  offset: uacpi_size,
  value: *mut uacpi_u16,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.pci_read16)(device, offset, value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_pci_read32(
  device: uacpi_handle,
  offset: uacpi_size,
  value: *mut uacpi_u32,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.pci_read32)(device, offset, value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_pci_write8(
  device: uacpi_handle,
  offset: uacpi_size,
  value: uacpi_u8,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.pci_write8)(device, offset, value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_pci_write16(
  device: uacpi_handle,
  offset: uacpi_size,
  value: uacpi_u16,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.pci_write16)(device, offset, value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_pci_write32(
  device: uacpi_handle,
  offset: uacpi_size,
  value: uacpi_u32,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.pci_write32)(device, offset, value)
}

#[doc = " Map a SystemIO address at [base, base + len) and return a kernel-implemented\n handle that can be used for reading and writing the IO range.\n\n NOTE: The x86 architecture uses the in/out family of instructions\n       to access the SystemIO address space."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_io_map(
  base: uacpi_io_addr,
  len: uacpi_size,
  out_handle: *mut uacpi_handle,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.io_map)(base, len, out_handle)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_io_unmap(handle: uacpi_handle) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.io_unmap)(handle)
}

#[doc = " Read/Write the IO range mapped via uacpi_kernel_io_map\n at a 0-based 'offset' within the range.\n\n NOTE:\n The x86 architecture uses the in/out family of instructions\n to access the SystemIO address space.\n\n You are NOT allowed to break e.g. a 4-byte access into four 1-byte accesses.\n Hardware ALWAYS expects accesses to be of the exact width."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_io_read8(
  arg1: uacpi_handle,
  offset: uacpi_size,
  out_value: *mut uacpi_u8,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.io_read8)(arg1, offset, out_value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_io_read16(
  arg1: uacpi_handle,
  offset: uacpi_size,
  out_value: *mut uacpi_u16,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.io_read16)(arg1, offset, out_value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_io_read32(
  arg1: uacpi_handle,
  offset: uacpi_size,
  out_value: *mut uacpi_u32,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.io_read32)(arg1, offset, out_value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_io_write8(
  arg1: uacpi_handle,
  offset: uacpi_size,
  in_value: uacpi_u8,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.io_write8)(arg1, offset, in_value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_io_write16(
  arg1: uacpi_handle,
  offset: uacpi_size,
  in_value: uacpi_u16,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.io_write16)(arg1, offset, in_value)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_io_write32(
  arg1: uacpi_handle,
  offset: uacpi_size,
  in_value: uacpi_u32,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.io_write32)(arg1, offset, in_value)
}

#[doc = " Allocate a block of memory of 'size' bytes.\n The contents of the allocated memory are unspecified."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_alloc(
  size: uacpi_size,
) -> *mut ::core::ffi::c_void {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.alloc)(size)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_free(mem: *mut ::core::ffi::c_void) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.free)(mem)
}

#[doc = " Returns the number of nanosecond ticks elapsed since boot,\n strictly monotonic."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_get_nanoseconds_since_boot() -> uacpi_u64
{
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.get_nanoseconds_since_boot)()
}

#[doc = " Spin for N microseconds."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_stall(usec: uacpi_u8) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.stall)(usec)
}

#[doc = " Sleep for N milliseconds."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_sleep(msec: uacpi_u64) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.sleep)(msec)
}

#[doc = " Create/free an opaque non-recursive kernel mutex object."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_create_mutex() -> uacpi_handle {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.create_mutex)()
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_free_mutex(arg1: uacpi_handle) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.free_mutex)(arg1)
}

#[doc = " Create/free an opaque kernel (semaphore-like) event object."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_create_event() -> uacpi_handle {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.create_event)()
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_free_event(arg1: uacpi_handle) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.free_event)(arg1)
}

#[doc = " Returns a unique identifier of the currently executing thread.\n\n The returned thread id cannot be UACPI_THREAD_ID_NONE."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_get_thread_id() -> uacpi_thread_id {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.get_thread_id)()
}

#[doc = " Disable interrupts and return an kernel-defined value representing the\n \"before\" state. This value is used in the subsequent call to restore the\n prior state.\n\n Note that this is talking about ALL interrupts on the current CPU, not just\n those installed by uACPI. This is typically achieved by executing the 'cli'\n instruction on x86, 'msr daifset, #3' on aarch64 etc."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_disable_interrupts()
-> uacpi_interrupt_state {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.disable_interrupts)()
}

#[doc = " Restore the state of the interrupt flags to the kernel-defined value provided\n in 'state'."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_restore_interrupts(
  state: uacpi_interrupt_state,
) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.restore_interrupts)(state)
}

#[doc = " Try to acquire the mutex with a millisecond timeout.\n\n The timeout value has the following meanings:\n 0x0000 - Attempt to acquire the mutex once, in a non-blocking manner\n 0x0001...0xFFFE - Attempt to acquire the mutex for at least 'timeout'\n                   milliseconds\n 0xFFFF - Infinite wait, block until the mutex is acquired\n\n The following are possible return values:\n 1. UACPI_STATUS_OK - successful acquire operation\n 2. UACPI_STATUS_TIMEOUT - timeout reached while attempting to acquire (or the\n                           single attempt to acquire was not successful for\n                           calls with timeout=0)\n 3. Any other value - signifies a host internal error and is treated as such"]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_acquire_mutex(
  arg1: uacpi_handle,
  arg2: uacpi_u16,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.acquire_mutex)(arg1, arg2)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_release_mutex(arg1: uacpi_handle) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.release_mutex)(arg1)
}

#[doc = " Try to wait for an event (counter > 0) with a millisecond timeout.\n A timeout value of 0xFFFF implies infinite wait.\n\n The internal counter is decremented by 1 if wait was successful.\n\n A successful wait is indicated by returning UACPI_TRUE."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_wait_for_event(
  arg1: uacpi_handle,
  arg2: uacpi_u16,
) -> uacpi_bool {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.wait_for_event)(arg1, arg2)
}

#[doc = " Signal the event object by incrementing its internal counter by 1.\n\n This function may be used in interrupt contexts."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_signal_event(arg1: uacpi_handle) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.signal_event)(arg1)
}

#[doc = " Reset the event counter to 0."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_reset_event(arg1: uacpi_handle) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.reset_event)(arg1)
}

#[doc = " Handle a firmware request.\n\n Currently either a Breakpoint or Fatal operators."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_handle_firmware_request(
  arg1: *mut uacpi_firmware_request,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.handle_firmware_request)(arg1)
}

#[doc = " Install an interrupt handler at 'irq', 'ctx' is passed to the provided\n handler for every invocation.\n\n 'out_irq_handle' is set to a kernel-implemented value that can be used to\n refer to this handler from other API."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_install_interrupt_handler(
  irq: uacpi_u32,
  arg1: uacpi_interrupt_handler,
  ctx: uacpi_handle,
  out_irq_handle: *mut uacpi_handle,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.install_interrupt_handler)(irq, arg1, ctx, out_irq_handle)
}

#[doc = " Uninstall an interrupt handler. 'irq_handle' is the value returned via\n 'out_irq_handle' during installation."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_uninstall_interrupt_handler(
  arg1: uacpi_interrupt_handler,
  irq_handle: uacpi_handle,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.uninstall_interrupt_handler)(arg1, irq_handle)
}

#[doc = " Create/free a kernel spinlock object.\n\n Unlike other types of locks, spinlocks may be used in interrupt contexts."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_create_spinlock() -> uacpi_handle {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.create_spinlock)()
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_free_spinlock(arg1: uacpi_handle) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.free_spinlock)(arg1)
}

#[doc = " Lock/unlock helpers for spinlocks.\n\n These are expected to disable interrupts, returning the previous state of cpu\n flags, that can be used to possibly re-enable interrupts if they were enabled\n before.\n\n Note that lock is infalliable."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_lock_spinlock(
  arg1: uacpi_handle,
) -> uacpi_cpu_flags {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.lock_spinlock)(arg1)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_unlock_spinlock(
  arg1: uacpi_handle,
  arg2: uacpi_cpu_flags,
) {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.unlock_spinlock)(arg1, arg2)
}

#[doc = " Schedules deferred work for execution.\n Might be invoked from an interrupt context."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_schedule_work(
  arg1: uacpi_work_type,
  arg2: uacpi_work_handler,
  ctx: uacpi_handle,
) -> uacpi_status {
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.schedule_work)(arg1, arg2, ctx)
}

#[doc = " Waits for two types of work to finish:\n 1. All in-flight interrupts installed via uacpi_kernel_install_interrupt_handler\n 2. All work scheduled via uacpi_kernel_schedule_work\n\n Note that the waits must be done in this order specifically."]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn uacpi_kernel_wait_for_work_completion() -> uacpi_status
{
  let api = &*UACPI_API_PTR.load(core::sync::atomic::Ordering::Relaxed);
  (api.wait_for_work_completion)()
}
